import { Item, PrivateEvidence, User, CampusNotification, AuditLog } from '../types';

export const CURRENT_USER: User = {
  uid: 'user_alex_01',
  email: 'alex.rivera@campus.edu',
  displayName: 'Alex Rivera',
  role: 'student',
  campusVerified: true,
  department: 'Computer Science & Engineering',
  studentId: 'CS-2024-8891',
  recoveryRating: 98,
  stats: {
    lostReported: 1,
    foundReported: 2,
    recoveredCount: 3,
  },
};

export const MODERATOR_USER: User = {
  uid: 'mod_sarah_99',
  email: 's.jenkins@campus-security.edu',
  displayName: 'Officer Sarah Jenkins',
  role: 'moderator',
  campusVerified: true,
  department: 'Campus Safety & Lost Desk',
  studentId: 'FAC-SAFE-402',
  recoveryRating: 100,
  stats: {
    lostReported: 0,
    foundReported: 14,
    recoveredCount: 89,
  },
};

export const CAMPUS_LOCATIONS = [
  { id: 'loc_lib_fl1', name: 'Main Campus Library — Ground Floor Lobby', zone: 'Library' },
  { id: 'loc_lib_fl2', name: 'Main Campus Library — 2nd Floor Quiet Study', zone: 'Library' },
  { id: 'loc_cafe_north', name: 'Student Union Cafeteria — North Hall', zone: 'Dining' },
  { id: 'loc_sci_lab3', name: 'Science Complex — Chem Lab 304', zone: 'Academic' },
  { id: 'loc_eng_hall', name: 'Engineering Quad — Turing Auditorium', zone: 'Academic' },
  { id: 'loc_sports_gym', name: 'Recreation Center — Basketball Arena', zone: 'Athletics' },
  { id: 'loc_dorm_ash', name: 'Ashford Residence Hall — Common Room', zone: 'Housing' },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item_lebron_21',
    type: 'found',
    category: 'clothing',
    subcategory: 'Sneakers',
    title: 'LeBron XXI Queen Conch (Size 12)',
    brand: 'Nike',
    color: 'Queen Conch',
    locationId: 'loc_sports_gym',
    locationName: 'Recreation Center — Basketball Arena',
    incidentDate: '2026-10-07T10:15:00Z',
    approximateTime: '10:15 AM',
    publicDescription: 'The LeBron XXI has a cabling system that works with Zoom Air cushioning and a light, low-to-the-ground design, giving you agile fluidity and explosiveness without excess weight. Left by bench court 3.',
    imageUrls: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80',
    ],
    status: 'active',
    riskTier: 2,
    reporterId: 'user_marcus_22',
    reporterName: 'Marcus Vance',
    hasPrivateEvidence: true,
    createdAt: '2026-10-07T10:30:00Z',
    updatedAt: '2026-10-07T10:30:00Z',
  },
  {
    id: 'item_kd_16',
    type: 'found',
    category: 'clothing',
    subcategory: 'Sneakers',
    title: 'KD16 Wanda (Size 11.5)',
    brand: 'Nike',
    color: 'Mint Green',
    locationId: 'loc_sports_gym',
    locationName: 'Recreation Center — Locker Room A',
    incidentDate: '2026-10-07T08:45:00Z',
    approximateTime: '8:45 AM',
    publicDescription: 'Mint green lightweight basketball shoes with multi-layer mesh and responsive full-length Air Zoom Strobel cushioning.',
    imageUrls: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=80',
    ],
    status: 'active',
    riskTier: 2,
    reporterId: 'mod_sarah_99',
    reporterName: 'Officer Sarah Jenkins',
    hasPrivateEvidence: true,
    createdAt: '2026-10-07T09:00:00Z',
    updatedAt: '2026-10-07T09:00:00Z',
  },
  {
    id: 'item_found_01',
    type: 'found',
    category: 'electronics',
    subcategory: 'Headphones',
    title: 'Black Sony Over-Ear Noise Cancelling Headphones',
    brand: 'Sony',
    color: 'Black',
    locationId: 'loc_lib_fl2',
    locationName: 'Main Campus Library — 2nd Floor Quiet Study',
    incidentDate: '2026-10-06T14:30:00Z',
    approximateTime: '2:30 PM',
    publicDescription: 'Found black over-ear headphones left on desk #14 in the quiet study room near the window.',
    imageUrls: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'active',
    riskTier: 2,
    reporterId: 'user_marcus_22',
    reporterName: 'Marcus Vance',
    hasPrivateEvidence: true,
    createdAt: '2026-10-06T15:00:00Z',
    updatedAt: '2026-10-06T15:00:00Z',
  },
  {
    id: 'item_lost_01',
    type: 'lost',
    category: 'electronics',
    subcategory: 'Headphones',
    title: 'Sony WH-1000XM4 Black Wireless Headphones',
    brand: 'Sony',
    color: 'Black',
    locationId: 'loc_lib_fl2',
    locationName: 'Main Campus Library — 2nd Floor Quiet Study',
    incidentDate: '2026-10-06T13:45:00Z',
    approximateTime: '1:45 PM',
    publicDescription: 'Left my black Sony headphones on the 2nd floor desk area while taking a phone call.',
    imageUrls: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'matched',
    riskTier: 2,
    reporterId: 'user_alex_01', // Owned by current user
    reporterName: 'Alex Rivera',
    hasPrivateEvidence: true,
    createdAt: '2026-10-06T16:20:00Z',
    updatedAt: '2026-10-06T16:20:00Z',
  },
  {
    id: 'item_found_02',
    type: 'found',
    category: 'electronics',
    subcategory: 'Laptop',
    title: 'Space Gray Apple MacBook Pro 14"',
    brand: 'Apple',
    color: 'Space Gray',
    locationId: 'loc_eng_hall',
    locationName: 'Engineering Quad — Turing Auditorium',
    incidentDate: '2026-10-05T17:15:00Z',
    approximateTime: '5:15 PM',
    publicDescription: 'Found Apple laptop left on row F after CS 301 lecture. Turned into Safe Desk.',
    imageUrls: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'claim_pending',
    riskTier: 3, // High-value / sensitive
    reporterId: 'mod_sarah_99',
    reporterName: 'Officer Sarah Jenkins',
    hasPrivateEvidence: true,
    createdAt: '2026-10-05T18:00:00Z',
    updatedAt: '2026-10-05T18:00:00Z',
  },
  {
    id: 'item_found_03',
    type: 'found',
    category: 'bags_wallets',
    subcategory: 'Wallet',
    title: 'Brown Leather Bi-fold Wallet',
    brand: 'Bellroy',
    color: 'Brown',
    locationId: 'loc_cafe_north',
    locationName: 'Student Union Cafeteria — North Hall',
    incidentDate: '2026-10-07T09:10:00Z',
    approximateTime: '9:10 AM',
    publicDescription: 'Found brown slim wallet by the smoothie counter. Contains cards and campus access pass.',
    imageUrls: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'active',
    riskTier: 3,
    reporterId: 'user_elena_54',
    reporterName: 'Elena Rostova',
    hasPrivateEvidence: true,
    createdAt: '2026-10-07T09:30:00Z',
    updatedAt: '2026-10-07T09:30:00Z',
  },
  {
    id: 'item_found_04',
    type: 'found',
    category: 'accessories',
    subcategory: 'Water Bottle',
    title: 'Forest Green Hydro Flask 32oz',
    brand: 'Hydro Flask',
    color: 'Green',
    locationId: 'loc_sports_gym',
    locationName: 'Recreation Center — Basketball Arena',
    incidentDate: '2026-10-06T19:00:00Z',
    approximateTime: '7:00 PM',
    publicDescription: 'Green stainless steel insulated water bottle with flex straw cap found on bleachers.',
    imageUrls: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'active',
    riskTier: 1, // Low risk
    reporterId: 'user_jake_11',
    reporterName: 'Jake Tyler',
    hasPrivateEvidence: true,
    createdAt: '2026-10-06T20:10:00Z',
    updatedAt: '2026-10-06T20:10:00Z',
  },
  {
    id: 'item_lost_02',
    type: 'lost',
    category: 'books_stationery',
    subcategory: 'Calculator',
    title: 'TI-84 Plus CE Graphing Calculator (Teal/Mint)',
    brand: 'Texas Instruments',
    color: 'Teal',
    locationId: 'loc_sci_lab3',
    locationName: 'Science Complex — Chem Lab 304',
    incidentDate: '2026-10-07T08:30:00Z',
    approximateTime: '8:30 AM',
    publicDescription: 'Mint green graphing calculator in slide case. Needed for calculus exam tomorrow!',
    imageUrls: [
      'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'active',
    riskTier: 1,
    reporterId: 'user_alex_01',
    reporterName: 'Alex Rivera',
    hasPrivateEvidence: true,
    createdAt: '2026-10-07T09:00:00Z',
    updatedAt: '2026-10-07T09:00:00Z',
  },
];

export const INITIAL_PRIVATE_EVIDENCE: Record<string, PrivateEvidence> = {
  item_lebron_21: {
    itemId: 'item_lebron_21',
    reporterId: 'user_marcus_22',
    secretQuestions: [
      {
        id: 'q_leb1',
        prompt: 'What size is printed on the interior tongue tag and what special laces are included?',
        expectedAnswer: 'Size 12 with extra rose gold metallic aglet laces',
      },
    ],
    finderPrivateNotes: 'Stored in gym manager office basket with orange tag.',
    createdAt: '2026-10-07T10:30:00Z',
  },
  item_kd_16: {
    itemId: 'item_kd_16',
    reporterId: 'mod_sarah_99',
    secretQuestions: [
      {
        id: 'q_kd1',
        prompt: 'Describe any custom insole or initials written inside the heel counter.',
        expectedAnswer: 'Wanda tribute graphic on left insole and size 11.5',
      },
    ],
    finderPrivateNotes: 'Checked into Safety Locker #2A.',
    createdAt: '2026-10-07T09:00:00Z',
  },
  item_found_01: {
    itemId: 'item_found_01',
    reporterId: 'user_marcus_22',
    secretQuestions: [
      {
        id: 'q1',
        prompt: 'Describe any specific sticker, scratch, or accessory attached to the headphones or case.',
        expectedAnswer: 'small green github octocat sticker on left inner ear band and slight scratch near power toggle',
      },
      {
        id: 'q2',
        prompt: 'What custom color or audio cable was inside the carrying pouch?',
        expectedAnswer: 'braided orange auxiliary cable',
      },
    ],
    finderPrivateNotes: 'Headphone case has a small carabiner clip with a silver key.',
    createdAt: '2026-10-06T15:00:00Z',
  },
  item_lost_01: {
    itemId: 'item_lost_01',
    reporterId: 'user_alex_01',
    serialNumber: 'S01-9982412-B',
    secretQuestions: [
      {
        id: 'q1',
        prompt: 'Describe any specific sticker or marking on the headphones.',
        expectedAnswer: 'octocat sticker on left inner ear band',
      },
    ],
    createdAt: '2026-10-06T16:20:00Z',
  },
  item_found_02: {
    itemId: 'item_found_02',
    reporterId: 'mod_sarah_99',
    serialNumber: 'C02G99XYMD6M',
    secretQuestions: [
      {
        id: 'q_mac1',
        prompt: 'Provide the MacBook serial number or describe the desktop wallpaper / user account name.',
        expectedAnswer: 'C02G99XYMD6M',
      },
      {
        id: 'q_mac2',
        prompt: 'What stickers are on the outer shell cover?',
        expectedAnswer: 'Rust programming logo and NASA space shuttle sticker',
      },
    ],
    finderPrivateNotes: 'Kept securely in Safe Locker #4B at Main Campus Safety Office.',
    createdAt: '2026-10-05T18:00:00Z',
  },
  item_found_03: {
    itemId: 'item_found_03',
    reporterId: 'user_elena_54',
    secretQuestions: [
      {
        id: 'q_wal1',
        prompt: 'State the exact initials or full name on the ID card inside the wallet.',
        expectedAnswer: 'Alex Rivera',
      },
      {
        id: 'q_wal2',
        prompt: 'What distinctive card or transit pass is stored in the front pull tab?',
        expectedAnswer: 'Metro Clipper Card with blue sticker',
      },
    ],
    createdAt: '2026-10-07T09:30:00Z',
  },
  item_found_04: {
    itemId: 'item_found_04',
    reporterId: 'user_jake_11',
    secretQuestions: [
      {
        id: 'q_bot1',
        prompt: 'Describe any stickers or initials engraved on the bottom or side of the bottle.',
        expectedAnswer: 'National Parks sticker with Yosemite half dome',
      },
    ],
    createdAt: '2026-10-06T20:10:00Z',
  },
};

export const INITIAL_NOTIFICATIONS: CampusNotification[] = [
  {
    id: 'notif_01',
    recipientId: 'user_alex_01',
    title: 'Potential Match Detected! (94%)',
    message: 'A Found report matching your Lost Sony Headphones was submitted at Library 2nd floor.',
    type: 'match_found',
    linkTarget: 'item_found_01',
    read: false,
    createdAt: '2026-10-06T16:25:00Z',
  },
  {
    id: 'notif_02',
    recipientId: 'user_alex_01',
    title: 'Verification Step Available',
    message: 'Review ownership challenge questions to securely claim your headphones.',
    type: 'claim_update',
    linkTarget: 'item_found_01',
    read: false,
    createdAt: '2026-10-06T17:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_01',
    actorId: 'user_marcus_22',
    actorName: 'Marcus Vance',
    action: 'REPORT_CREATED',
    targetType: 'item',
    targetId: 'item_found_01',
    timestamp: '2026-10-06T15:00:00Z',
    metadata: { type: 'found', category: 'electronics' },
  },
  {
    id: 'audit_02',
    actorId: 'user_alex_01',
    actorName: 'Alex Rivera',
    action: 'REPORT_CREATED',
    targetType: 'item',
    targetId: 'item_lost_01',
    timestamp: '2026-10-06T16:20:00Z',
    metadata: { type: 'lost', category: 'electronics' },
  },
  {
    id: 'audit_03',
    actorId: 'system_matching',
    actorName: 'FYND Engine',
    action: 'MATCH_DETECTED',
    targetType: 'item',
    targetId: 'item_found_01',
    timestamp: '2026-10-06T16:20:05Z',
    metadata: { score: 94, classification: 'strong' },
  },
];
